### ISSUE TITLE
Your icons are way too unnoticable in dark mode

### ISSUE THREAD

**Issue by Antosser** [AureumApes/AureumApes#1]
![image](https://user-images.githubusercontent.com/71790328/164509702-55d6cb49-1cf0-4754-a1c8-05d0a07ca2a2.png)

**Comment by AureumApes** [comment]
Ohh thank you.
ill fix it

**Comment by AureumApes** [comment]
![image](https://user-images.githubusercontent.com/76166556/164699402-72c71b6d-b173-4e3a-9b9c-9333d2aa392a.png)
Fixed it
